#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,keys,php,log/php} \
	/run/php \
	/var/lib/nginx/tmp/client_body

# copy config files
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
	cp /defaults/default /config/nginx/site-confs/default
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html

# fix timezone in php.ini
sed -i "s#;date.timezone =.*#date.timezone = $TZ#g" /etc/php/7.0/cli/php.ini
sed -i "s#;date.timezone =.*#date.timezone = $TZ#g" /etc/php/7.0/fpm/php.ini
#fix php-fpm log location
sed -i "s#error_log = /var/log/php7.0-fpm.log#error_log = /config/log/php/error.log#g" /etc/php/7.0/fpm/php-fpm.conf
#fix php-fpm user
sed -i "s#user = www-data.*#user = abc#g" /etc/php/7.0/fpm/pool.d/www.conf
sed -i "s#group = www-data.*#group = abc#g" /etc/php/7.0/fpm/pool.d/www.conf

#filerun config php
cp /defaults/filerun.ini /etc/php/7.0/fpm/conf.d


# permissions
chown -R abc:abc \
	/config \
	/run \
	/var/lib/nginx
chmod -R g+w \
	/config/{nginx,www}
chmod -R 644 /etc/logrotate.d /config/log
